services:
  test:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: development
    command:
      - sh
      - -c
      - npm run prisma:generate && npm run test:integration
    environment:
      TESTCONTAINERS_HOST_OVERRIDE: localhost
    network_mode: host
    user: '0:0'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
