export const ADJECTIVES = Object.freeze([
  'Agile',
  'Amber',
  'Bold',
  'Brave',
  'Bright',
  'Calm',
  'Clever',
  'Crimson',
  'Daring',
  'Emerald',
  'Gentle',
  'Golden',
  'Grand',
  'Hidden',
  'Honest',
  'Jolly',
  'Kind',
  'Lively',
  'Lucky',
  'Merry',
  'Mighty',
  'Nimble',
  'Noble',
  'Quiet',
  'Rapid',
  'Royal',
  'Silent',
  'Silver',
  'Steady',
  'Swift',
  'Valiant',
  'Wise',
] as const);

export const NOUNS = Object.freeze([
  'Beacon',
  'Bear',
  'Bishop',
  'Castle',
  'Charger',
  'Cipher',
  'Comet',
  'Crown',
  'Dragon',
  'Falcon',
  'File',
  'Fork',
  'Fox',
  'Gambit',
  'Harbor',
  'Knight',
  'Lion',
  'Meadow',
  'Monarch',
  'Nova',
  'Orbit',
  'Pawn',
  'Pin',
  'Rank',
  'Raven',
  'Rider',
  'Rook',
  'Stallion',
  'Summit',
  'Tempo',
  'Tiger',
  'Wolf',
] as const);

export const AVATARS = Object.freeze([
  { cdnPath: '/avatars/knight-amber-01.webp', key: 'knight_amber_01' },
  { cdnPath: '/avatars/knight-bay-02.webp', key: 'knight_bay_02' },
  { cdnPath: '/avatars/knight-bay-03.webp', key: 'knight_bay_03' },
  { cdnPath: '/avatars/knight-black-01.webp', key: 'knight_black_01' },
  { cdnPath: '/avatars/knight-chestnut-01.webp', key: 'knight_chestnut_01' },
  { cdnPath: '/avatars/knight-gray-02.webp', key: 'knight_gray_02' },
  { cdnPath: '/avatars/knight-palomino-01.webp', key: 'knight_palomino_01' },
  { cdnPath: '/avatars/knight-white-02.webp', key: 'knight_white_02' },
] as const);

export type AvatarKey = (typeof AVATARS)[number]['key'];
