import { parsePublicEnvironment } from './environment.schema';

export const publicEnvironment = parsePublicEnvironment({
  NEXT_PUBLIC_API_ORIGIN: process.env.NEXT_PUBLIC_API_ORIGIN,
  NEXT_PUBLIC_APP_ORIGIN: process.env.NEXT_PUBLIC_APP_ORIGIN,
  NEXT_PUBLIC_BUILD_SHA: process.env.NEXT_PUBLIC_BUILD_SHA,
  NEXT_PUBLIC_ENABLE_DEVTOOLS: process.env.NEXT_PUBLIC_ENABLE_DEVTOOLS,
  NEXT_PUBLIC_FF_FRONTEND_TELEMETRY:
    process.env.NEXT_PUBLIC_FF_FRONTEND_TELEMETRY,
  NEXT_PUBLIC_FF_LEARN_HUB: process.env.NEXT_PUBLIC_FF_LEARN_HUB,
  NEXT_PUBLIC_FF_LESSON_HERO_ART: process.env.NEXT_PUBLIC_FF_LESSON_HERO_ART,
  NEXT_PUBLIC_FF_SOUND_EFFECTS: process.env.NEXT_PUBLIC_FF_SOUND_EFFECTS,
  NEXT_PUBLIC_PROTOCOL_VERSION: process.env.NEXT_PUBLIC_PROTOCOL_VERSION,
  NEXT_PUBLIC_SOCKET_ORIGIN: process.env.NEXT_PUBLIC_SOCKET_ORIGIN,
});
